apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: velero-hostpath-exceptions
  namespace: velero
spec:
  exceptions:
  - policyName: restrict-host-path-write
    ruleNames:
    - require-readonly-hostpath
  match:
    any:
    - resources:
        kinds:
        - Pod
        - DaemonSet
        namespaces:
        - velero
        names:
        - node-agent*
