apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: velero-privileged-exceptions
  namespace: velero
spec:
  exceptions:
  - policyName: disallow-privileged-containers
    ruleNames:
    - priviledged-containers
  match:
    any:
    - resources:
        kinds:
        - Pod
        - DaemonSet
        namespaces:
        - velero
        names:
        - node-agent*
