apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: mattermost-object-storage-external-names-exception
  namespace: mattermost
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - mattermost
        names:
        - mattermost-object-store
