bundle:
  deploy:
    zarf-packages:
      init:
        set:
          # TODO - remove this if/when functionality is restored upstream
          REGISTRY_HPA_ENABLE: false
      metallb:
        set:
          # dev
          IP_ADDRESS_POOL: "24.0.132.244/30"
          # test
          # IP_ADDRESS_POOL: "24.0.132.248/30"
      dubbd-rke2:
        set:
          # TODO - replace these blanket exceptions with more targeted kyverno policy exceptions
          EXEMPT_NAMESPACES: '["zarf", "rook-ceph", "metallb-system"]'
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      software-factory-idam-gitlab:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      software-factory-idam-sonarqube:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      software-factory-idam-realm:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      uds-idam:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      gitlab:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      sonarqube:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          SONARQUBE_IDAM_REALM_URL: "https://keycloak.mtsi-dev.bigbang.dev/auth/realms/baby-yoda"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
          # SONARQUBE_IDAM_REALM_URL: "https://keycloak.mtsi.bigbang.dev/auth/realms/baby-yoda"
      jira:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      confluence:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      mattermost:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
      nexus:
        set:
          # dev
          DOMAIN: "mtsi-dev.bigbang.dev"
          # test
          # DOMAIN: "mtsi.bigbang.dev"
