bundle:
  deploy:
    zarf-packages:
      metallb:
        set:
          IP_ADDRESS_POOL: "24.0.132.240/28"
      dubbd-rke2:
        set:
          # TODO - replace these blanket exceptions with more targeted kyverno policy exceptions
          EXEMPT_NAMESPACES: '["zarf", "rook-ceph", "metallb-system"]'
          DOMAIN: "mtsi.bigbang.dev"
      uds-idam:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      gitlab:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      sonarqube:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      jira:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      confluence:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      mattermost:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      nexus:
        set:
          DOMAIN: "mtsi.bigbang.dev"
