bundle:
  deploy:
    zarf-packages:
      init:
        set:
          # TODO - remove this if/when functionality is restored upstream
          REGISTRY_HPA_ENABLE: false
      metallb:
        set:
          # dev
          IP_ADDRESS_POOL: "24.0.132.244/30"
          # test
          # IP_ADDRESS_POOL: "24.0.132.248/30"
      dubbd-rke2:
        set:
          # TODO - replace these blanket exceptions with more targeted kyverno policy exceptions
          EXEMPT_NAMESPACES: '["zarf", "rook-ceph", "metallb-system"]'
          DOMAIN: "mtsi.bigbang.dev"
      uds-idam:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      gitlab:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      sonarqube:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      jira:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      confluence:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      mattermost:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      nexus:
        set:
          DOMAIN: "mtsi.bigbang.dev"
