package:
  create:
    max_package_size: "1000000000"
    # These values are sourced from and updated with https://github.com/defenseunicorns/zarf/blob/main/zarf-config.toml
    set:
      agent_image_domain: "ghcr.io/"
      agent_image: "zarf-dev/zarf/agent"

      # Tag for the zarf injector binary to use
      injector_version: '2024-07-22'
      injector_amd64_shasum: '8463bfd66930a4b26c665b51f25e8a32ed5948068bae49987013c89173394478'
      injector_arm64_shasum: 'b905e647e0d7876cfd5b665632cfc43ad919dc60408f7236c5b541c53277b503'

      registry_image_domain: ""
      registry_image: "library/registry"
      registry_image_tag: "2.8.3"

      gitea_image: 'gitea/gitea:1.21.5-rootless'
