variables:
  - name: ARCH
    description: "What architecture to use"
    default: "amd64"

tasks:
  # Build directory
  - name: build-dir
    description: Create build directory
    actions:
      - cmd: mkdir -p build

  # Bundles
  - name: bundle
    description: Create the UDS Bundle with SWF on UDS Core
    actions:
      - cmd: ./uds create ./bundles/uds-core-swf --architecture=${ARCH} --confirm
      - cmd: mv ./bundles/uds-core-swf/uds-bundle-* ./build

  # Packages
  - name: database-manifest-packages
    description: Create database manifest packages
    actions:
      - cmd: ./uds zarf package create ./packages/databases/gitlab/secret --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
      - cmd: ./uds zarf package create ./packages/databases/sonarqube/secret --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: keycloak-config-wrapper-package
    description: Create the keycloak configurations shim loader
    actions:
      - cmd: ./uds zarf package create ./packages/keycloak-config-wrapper --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: object-store-packages
    description: Create the object storage packages
    actions:
      - cmd: ./uds zarf package create ./packages/object-store/gitlab --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: additional-manifests-package
    description: Create package create additional manifests needed.
    actions:
      - cmd: ./uds zarf package create ./packages/additional-manifests --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: nutanix-csi-package
    description: Create Nutanix CSI driver package.
    actions:
      - cmd: ./uds zarf package create ./packages/nutanix-csi --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: cert-manager-package
    description: Create cert-manager package.
    actions:
      - cmd: ./uds zarf package create ./packages/cert-manager --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: trust-manager-package
    description: Create trust-manager package.
    actions:
      - cmd: ./uds zarf package create ./packages/trust-manager --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: trust-bundles-package
    description: Create trust-bundle package for adding custom CAs.
    actions:
      - cmd: ./uds zarf package create ./packages/trust-bundles --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
