variables:
  - name: ARCH
    description: "What architecture to use"
    default: "amd64"

tasks:
  # Build directory
  - name: build-dir
    description: Create build directory
    actions:
      - cmd: mkdir build -p

  # Bundles
  - name: bundle
    description: Create the UDS Bundle with SWF on UDS Core
    actions:
      - cmd: ./uds create ./bundles/uds-core-swf --architecture=${ARCH} --confirm
      - cmd: mv ./bundles/uds-core-swf/uds-bundle-* ./build

  # Packages
  - name: database-manifest-packages
    description: Create database manifest packages
    actions:
      - cmd: ./uds zarf package create ./packages/databases/confluence/secret --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
      - cmd: ./uds zarf package create ./packages/databases/gitlab/secret --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
      - cmd: ./uds zarf package create ./packages/databases/jira/secret --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
      - cmd: ./uds zarf package create ./packages/databases/sonarqube/secret --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: gitlab-redis-secret-package
    description: Create package for the gitlab redis secret
    actions:
      - cmd: ./uds zarf package create ./packages/gitlab-redis --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: keycloak-config-wrapper-package
    description: Create the keycloak configurations shim loader
    actions:
      - cmd: ./uds zarf package create ./packages/keycloak-config-wrapper --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build      

  - name: namespaces-package
    description: Create the namespaces package
    actions:
      - cmd: ./uds zarf package create ./packages/namespaces --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: object-store-packages
    description: Create the object storage packages
    actions:
      - cmd: ./uds zarf package create ./packages/object-store/gitlab --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: additional-manifests-package
    description: Create package create additional manifests needed.
    actions:
      - cmd: ./uds zarf package create ./packages/additional-manifests --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
  
  # TODO - remove when multiple exemptions can be applied at once
  - name: additional-manifests-package-2
    description: Create package create additional manifests needed.
    actions:
      - cmd: ./uds zarf package create ./packages/additional-manifests/pepr-policy-exemptions/tmp-csi-exemption --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: init-package
    description: Create init package with Nutanix CSI driver.
    actions:
      - cmd: ZARF_CONFIG=./packages/init/zarf-config.yaml ./uds zarf package create ./packages/init --set AGENT_IMAGE_TAG=$(uds zarf version) --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
  
  - name: trustmanager-package
    description: Create trustmanager package.
    actions:
      - cmd: ./uds zarf package create ./packages/trustmanager --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: trust-bundles-package
    description: Create trust-bundle package for adding custom CAs.
    actions:
      - cmd: ./uds zarf package create ./packages/trust-bundles --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
