apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: nexus-postgres-external-names-exception
  namespace: nexus
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - nexus
        names:
        - nexus-postgres
