bundle:
  deploy:
    zarf-packages:
      init:
        set:
          # TODO - remove this if/when functionality is restored upstream
          REGISTRY_HPA_ENABLE: false
      metallb:
        set:
          IP_ADDRESS_POOL: "24.0.132.244/30"
      dubbd-rke2:
        set:
          # TODO - replace these blanket exceptions with more targeted kyverno policy exceptions
          EXEMPT_NAMESPACES: '["zarf", "rook-ceph", "metallb-system"]'
          DOMAIN: "mtsi-dev.bigbang.dev"
      software-factory-idam-gitlab:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
      software-factory-idam-realm:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
      keycloak-database-manifests:
        set:
          KEYCLOAK_DB_EXTERNAL_NAME: "keycloak-pg.mtsi-dev.bigbang.dev"
      uds-idam:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          KEYCLOAK_DB_USERNAME: "postgres"
          KEYCLOAK_DB_PASSWORD: "replace-me"
          KEYCLOAK_DB_NAME: "keycloakdb"
          KEYCLOAK_DB_ENDPOINT: "keycloak-postgres.keycloak.svc.cluster.local"
      gitlab-database-manifests:
        set:
          GITLAB_DB_EXTERNAL_NAME: "gitlab-pg.mtsi-dev.bigbang.dev"
          GITLAB_DB_PASSWORD: "replace-me"
      gitlab-object-store:
        set:
          ENDPOINT: "http://swf.objects.mtsi.bigbang.dev"
          ACCESS_KEY: "object-store-replace-access-key"
          SECRET_KEY: "object-store-replace-secret-key"
      gitlab:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          GITLAB_DB_NAME: "gitlabdb"
          GITLAB_DB_USERNAME: "postgres"
          GITLAB_PAGES_ENABLED: "true"
          GITLAB_SIGNUP_ENABLED: "false"
          BUCKET_SUFFIX: "-dev"
      sonarqube-database-manifests:
        set:
          SONARQUBE_DB_EXTERNAL_NAME: "sonarqube-pg.mtsi-dev.bigbang.dev"
          SONARQUBE_DB_PASSWORD: "replace-me"
      sonarqube:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          SONARQUBE_IDAM_REALM_URL: "https://keycloak.mtsi-dev.bigbang.dev/auth/realms/baby-yoda"
          SONARQUBE_DB_NAME: "sonarqubedb"
          SONARQUBE_DB_USERNAME: "postgres"
      jira-database-manifests:
        set:
          JIRA_DB_EXTERNAL_NAME: "jira-pg.mtsi-dev.bigbang.dev"
          JIRA_DB_PASSWORD: "replace-me"
      jira:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          JIRA_DB_NAME: "jiradb"
          JIRA_DB_USERNAME: "postgres"
      confluence-database-manifests:
        set:
          CONFLUENCE_DB_EXTERNAL_NAME: "confluence-pg.mtsi-dev.bigbang.dev"
          CONFLUENCE_DB_PASSWORD: "replace-me"
      confluence:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          CONFLUENCE_DB_NAME: "confluencedb"
          CONFLUENCE_DB_USERNAME: "postgres"
      mattermost-database-manifests:
        set:
          MATTERMOST_DB_EXTERNAL_NAME: "mattermost-pg.mtsi-dev.bigbang.dev"
          MATTERMOST_DB_PASSWORD: "replace-me"
          MATTERMOST_DB_USERNAME: "postgres"
          MATTERMOST_DB_NAME: "mattermostdb"
      mattermost-object-store:
        set:
          ACCESS_KEY: "object-store-replace-access-key"
          SECRET_KEY: "object-store-replace-secret-key"
      mattermost:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          MATTERMOST_BUCKET_SUFFIX: "-dev"
          MATTERMOST_FILE_STORE_ENDPOINT: "swf.objects.mtsi.bigbang.dev"
      nexus-database-manifests:
        set:
          NEXUS_DB_EXTERNAL_NAME: "nexus-pg.mtsi-dev.bigbang.dev"
          NEXUS_DB_PASSWORD: "replace-me"
      nexus:
        set:
          DOMAIN: "mtsi-dev.bigbang.dev"
          NEXUS_DB_NAME: "nexusdb"
          NEXUS_DB_USERNAME: "postgres"
