# Default values for nutanix-csi-storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# parameters

# Legacy mode
#
# if legacy set to true we keep the old reverse domain notation for CSI driver name (com.nutanix.csi).
# need to be set to true only if upgrade and initialy installed with helm package before 2.2.x
legacy: false

# Openshift settings
#

openshift:
  scc: false
  masterIscsiConfig: false
  workerIscsiConfig: false

# kubeletDir allows overriding the host location of kubelet's internal state.
kubeletDir: "/var/lib/kubelet"

# Global Settings for all pods

nodeSelector: {}
tolerations: []
imagePullPolicy: IfNotPresent

# Storage Class settings
#
# choose for which mode (Volume, File, Dynamic File) storageclass need to be created
volumeClass: true
volumeClassName: "nutanix-volume"
volumeClassRetention: "Delete"
# volumeClassDescription: ""
# volumeClassAnnotations: {}
# volumeClassLabels: {}

volumeSnapshotClassName: "nutanix-snapshot-class"
# volumeSnapshotClassAnnotations: {}
# volumeSnapshotClassLabels: {}

fileClass: false
fileClassName: "nutanix-file"
fileClassRetention: "Delete"
# fileClassAnnotations: {}
# fileClassLabels: {}

dynamicFileClass: true
dynamicFileClassName: "nutanix-dynamicfile"
dynamicFileClassRetention: "Delete"
# dynamicFileClassDescription: ""
# dynamicFileClassAnnotations: {}
# dynamicFileClassLabels: {}

# Default Storage Class settings
#
# Decide wich storageclass will be the default
# value are: none, volume, file, dynfile
defaultStorageClass: volume

# Nutanix Prism Elements settings
#
# Allow dynamic creation of Volumes and Fileshare
# needed if volumeClass or dynamicFileClass is set to true

## fully qualified domain name (FQDN) or the cluster virtual IP address (if one is not configured, use the virtual IP address of any Controller VM in the cluster).
prismEndPoint: ###ZARF_VAR_PRISM_ENDPOINT###
prismPort: 9440

## username of the Prism Element (PE) cluster admin
username: ###ZARF_VAR_PRISM_USERNAME###

## password for the PE cluster admin.
password: ###ZARF_VAR_PRISM_PASSWORD###

## secret name that stores Nutanix cluster credentials
secretName: ntnx-secret

## Nutanix Prism Elements Existing Secret
#

# if set to false a new secret will not be created
createSecret: true

## Volumes Settings
#

## name of the Nutanix storage container
storageContainer: ###ZARF_VAR_STORAGE_CONTAINER###

## Filesystem used in volume PV
fsType: xfs

lvmVolume: false
lvmDisks: 4

networkSegmentation: false

# Files Settings
#

## NFS server fully qualified domain name (FQDN) or IP address
# fileHost:

## path for the NFS share
# filePath:

# Dynamic Files Settings
#

## name of the file server. (As seen in the Prism Interface)
fileServerName: ###ZARF_VAR_DYNAMIC_FILE_STORE_NAME###

# Squash-type for dynamic files.
# Values are: none, root-squash, all-squash. Default is root-squash
dynamicFileSquashType: root-squash

# Volume metrics and CSI operations metrics configuration
#

servicemonitor:
  enabled: false
  labels:
    # This should match the serviceMonitorSelector logic configured
    # on the prometheus.
    k8s-app: csi-driver

# Pod pecific Settings
#

controller:
  replicas: 2
  image: ###ZARF_REGISTRY###/karbon/ntnx-csi:v2.6.6
  nodeSelector: {}
  tolerations: []

node:
  image: ###ZARF_REGISTRY###/karbon/ntnx-csi:v2.6.6
  nodeSelector: {}
  tolerations: []

sidecars:
  registrar:
    image: ###ZARF_REGISTRY###/sig-storage/csi-node-driver-registrar:v2.9.1
  provisioner:
    image: ###ZARF_REGISTRY###/sig-storage/csi-provisioner:v3.6.2
    imageLegacy: ###ZARF_REGISTRY###/sig-storage/csi-provisioner:v2.2.2
  snapshotter:
    image: ###ZARF_REGISTRY###/sig-storage/csi-snapshotter:v6.3.2
    imageBeta: ###ZARF_REGISTRY###/sig-storage/csi-snapshotter:v3.0.3
  resizer:
    image: ###ZARF_REGISTRY###/sig-storage/csi-resizer:v1.9.2
  livenessprobe:
    image: ###ZARF_REGISTRY###/sig-storage/livenessprobe:v2.11.0

# Used for deployment test in kind cluster
#

kindtest: false
