# Source: bigbang/templates/gitlab/secret-objectstore.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-object-store
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  connection: |-
    provider: AWS
    region: us-east-1
    aws_access_key_id: ###ZARF_VAR_ACCESS_KEY###
    aws_secret_access_key: ###ZARF_VAR_SECRET_KEY###
    endpoint: ###ZARF_VAR_ENDPOINT###
    aws_signature_version: 4
    path_style: true
  registry: |-
    s3:
      bucket: uds-gitlab-registry
      accesskey: ###ZARF_VAR_ACCESS_KEY###
      secretkey: ###ZARF_VAR_SECRET_KEY###
      regionendpoint: ###ZARF_VAR_ENDPOINT###
      region: us-east-1
      aws_signature_version: 4
      path_style: true
  backups: |-
    [default]
    access_key = ###ZARF_VAR_ACCESS_KEY###
    secret_key = ###ZARF_VAR_SECRET_KEY###
    host_base = ###ZARF_VAR_ENDPOINT###
    host_bucket = ###ZARF_VAR_ENDPOINT###
    bucket_location = us-east-1
    multipart_chunk_size_mb = 128
    use_https = False
