apiVersion: batch/v1
kind: Job
metadata:
  name: identity-config-loader
  namespace: keycloak
spec:
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: uds-config-sync
          # renovate: datasource=github-tags depName=defenseunicorns/uds-identity-config versioning=semver 
          image: ghcr.io/defenseunicorns/uds/identity-config:0.4.3
          command: 
            [
              "sh",
              "-c",
              # This command looks for the Zarf "data injection marker" which is a timestamped file that is injected after everything else and marks the injection as complete.
              'while [ ! -f /home/nonroot/marker ]; do echo "waiting for data sync" && sleep 1; done; echo "we are done waiting!"; /home/nonroot/sync.sh',
            ]
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: providers
              mountPath: /opt/keycloak/providers
            - name: data
              mountPath: /opt/keycloak/data
            - name: themes
              mountPath: /opt/keycloak/themes
            - name: conf
              mountPath: /opt/keycloak/conf
      restartPolicy: Never
      volumes:
        - name: providers
          persistentVolumeClaim: 
            claimName: keycloak-providers
        # jars are only copied into providers -- the rest won't matter, but are needed for file permissions in the sync script
        - name: conf
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: themes
          emptyDir: {}
