apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: gitlab-non-root-group-exception
  namespace: gitlab
spec:
  exceptions:
  - policyName: require-non-root-group
    ruleNames:
    - run-as-group
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - gitlab
        names:
        - deployment-gitlab-toolbox-backup*
        - gitlab-toolbox-backup*
