apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph # namespace:cluster
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: rook-ceph-tools
          image: quay.io/ceph/ceph:v18.2.1
          command:
            - /bin/bash
            - -c
            - |
              # Replicate the script from toolbox.sh inline so the ceph image
              # can be run directly, instead of requiring the rook toolbox
              CEPH_CONFIG="/etc/ceph/ceph.conf"
              MON_CONFIG="/etc/rook/mon-endpoints"
              KEYRING_FILE="/etc/ceph/keyring"

              # create a ceph config file in its default location so ceph/rados tools can be used
              # without specifying any arguments
              write_endpoints() {
                endpoints=$(cat ${MON_CONFIG})

                # filter out the mon names
                # external cluster can have numbers or hyphens in mon names, handling them in regex
                # shellcheck disable=SC2001
                mon_endpoints=$(echo "${endpoints}"| sed 's/[a-z0-9_-]\+=//g')

                DATE=$(date)
                echo "$DATE writing mon endpoints to ${CEPH_CONFIG}: ${endpoints}"
                  cat <<EOF > ${CEPH_CONFIG}
              [global]
              mon_host = ${mon_endpoints}

              [client.admin]
              keyring = ${KEYRING_FILE}
              EOF
              }

              # watch the endpoints config file and update if the mon endpoints ever change
              watch_endpoints() {
                # get the timestamp for the target of the soft link
                real_path=$(realpath ${MON_CONFIG})
                initial_time=$(stat -c %Z "${real_path}")
                while true; do
                  real_path=$(realpath ${MON_CONFIG})
                  latest_time=$(stat -c %Z "${real_path}")

                  if [[ "${latest_time}" != "${initial_time}" ]]; then
                    write_endpoints
                    initial_time=${latest_time}
                  fi

                  sleep 10
                done
              }

              # read the secret from an env var (for backward compatibility), or from the secret file
              ceph_secret=${ROOK_CEPH_SECRET}
              if [[ "$ceph_secret" == "" ]]; then
                ceph_secret=$(cat /var/lib/rook-ceph-mon/secret.keyring)
              fi

              # create the keyring file
              cat <<EOF > ${KEYRING_FILE}
              [${ROOK_CEPH_USERNAME}]
              key = ${ceph_secret}
              EOF

              # write the initial config file
              write_endpoints

              # continuously update the mon endpoints if they fail over
              watch_endpoints
          imagePullPolicy: IfNotPresent
          tty: true
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 0
            capabilities:
              drop: ["ALL"]
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
          volumeMounts:
            - mountPath: /etc/ceph
              name: ceph-config
            - name: mon-endpoint-volume
              mountPath: /etc/rook
            - name: ceph-admin-secret
              mountPath: /var/lib/rook-ceph-mon
              readOnly: true
            - mountPath: /var/lib/ceph/osd/ceph-0
              name: activate-osd
      # initContainers:
      #   - command:
      #     - /bin/bash
      #     - -c
      #     - "\nset -o errexit\nset -o pipefail\nset -o nounset # fail if variables are
      #       unset\nset -o xtrace\n\nOSD_ID=\"$ROOK_OSD_ID\"\nCEPH_FSID=cd940091-c635-449f-92d4-d017f5f8175d\nOSD_UUID=32ca9167-1d8d-4611-b862-4c5df148e60c\nOSD_STORE_FLAG=\"--bluestore\"\nOSD_DATA_DIR=/var/lib/ceph/osd/ceph-\"$OSD_ID\"\nCV_MODE=raw\nDEVICE=\"$ROOK_BLOCK_PATH\"\n\n#
      #       \"ceph.conf\" must have the \"fsid\" global configuration to activate encrypted
      #       OSDs\n# after the following Ceph's PR is merged.\n# https://github.com/ceph/ceph/commit/25655e5a8829e001adf467511a6bde8142b0a575\n#
      #       This limitation will be removed later. After that, we can remove this\n#
      #       fsid injection code. Probably a good time is when to remove Quincy support.\n#
      #       https://github.com/rook/rook/pull/10333#discussion_r892817877\ncp --no-preserve=mode
      #       /etc/temp-ceph/ceph.conf /etc/ceph/ceph.conf\npython3 -c \"\nimport configparser\n\nconfig
      #       = configparser.ConfigParser()\nconfig.read('/etc/ceph/ceph.conf')\n\nif
      #       not config.has_section('global'):\n    config['global'] = {}\n\nif not config.has_option('global','fsid'):\n
      #       \   config['global']['fsid'] = '$CEPH_FSID'\n\nwith open('/etc/ceph/ceph.conf',
      #       'w') as configfile:\n    config.write(configfile)\n\"\n\n# create new keyring\nceph
      #       -n client.admin auth get-or-create osd.\"$OSD_ID\" mon 'allow profile osd'
      #       mgr 'allow profile osd' osd 'allow *' -k /etc/ceph/admin-keyring-store/keyring\n\n#
      #       active the osd with ceph-volume\nif [[ \"$CV_MODE\" == \"lvm\" ]]; then\n\tTMP_DIR=$(mktemp
      #       -d)\n\n\t# activate osd\n\tceph-volume lvm activate --no-systemd \"$OSD_STORE_FLAG\"
      #       \"$OSD_ID\" \"$OSD_UUID\"\n\n\t# copy the tmpfs directory to a temporary
      #       directory\n\t# this is needed because when the init container exits, the
      #       tmpfs goes away and its content with it\n\t# this will result in the emptydir
      #       to be empty when accessed by the main osd container\n\tcp --verbose --no-dereference
      #       \"$OSD_DATA_DIR\"/* \"$TMP_DIR\"/\n\n\t# unmount the tmpfs since we don't
      #       need it anymore\n\tumount \"$OSD_DATA_DIR\"\n\n\t# copy back the content
      #       of the tmpfs into the original osd directory\n\tcp --verbose --no-dereference
      #       \"$TMP_DIR\"/* \"$OSD_DATA_DIR\"\n\n\t# retain ownership of files to the
      #       ceph user/group\n\tchown --verbose --recursive ceph:ceph \"$OSD_DATA_DIR\"\n\n\t#
      #       remove the temporary directory\n\trm --recursive --force \"$TMP_DIR\"\nelse\n\t#
      #       'ceph-volume raw list' (which the osd-prepare job uses to report OSDs on
      #       nodes)\n\t#  returns user-friendly device names which can change when systems
      #       reboot. To\n\t# keep OSD pods from crashing repeatedly after a reboot, we
      #       need to check if the\n\t# block device we have is still correct, and if
      #       it isn't correct, we need to\n\t# scan all the disks to find the right one.\n\tOSD_LIST=\"$(mktemp)\"\n\n\tfunction
      #       find_device() {\n\t\t# jq would be preferable, but might be removed for
      #       hardened Ceph images\n\t\t# python3 should exist in all containers having
      #       Ceph\n\t\tpython3 -c \"\nimport sys, json\nfor _, info in json.load(sys.stdin).items():\n\tif
      #       info['osd_id'] == $OSD_ID:\n\t\tprint(info['device'], end='')\n\t\tprint('found
      #       device: ' + info['device'], file=sys.stderr) # log the disk we found to
      #       stderr\n\t\tsys.exit(0)  # don't keep processing once the disk is found\nsys.exit('no
      #       disk found with OSD ID $OSD_ID')\n\"\n\t}\n\n\tceph-volume raw list \"$DEVICE\"
      #       > \"$OSD_LIST\"\n\tcat \"$OSD_LIST\"\n\n\tif ! find_device < \"$OSD_LIST\";
      #       then\n\t\tceph-volume raw list > \"$OSD_LIST\"\n\t\tcat \"$OSD_LIST\"\n\n\t\tDEVICE=\"$(find_device
      #       < \"$OSD_LIST\")\"\n\tfi\n\t[[ -z \"$DEVICE\" ]] && { echo \"no device\"
      #       ; exit 1 ; }\n\n\t# If a kernel device name change happens and a block device
      #       file\n\t# in the OSD directory becomes missing, this OSD fails to start\n\t#
      #       continuously. This problem can be resolved by confirming\n\t# the validity
      #       of the device file and recreating it if necessary.\n\tOSD_BLOCK_PATH=/var/lib/ceph/osd/ceph-$OSD_ID/block\n\tif
      #       [ -L $OSD_BLOCK_PATH -a \"$(readlink $OSD_BLOCK_PATH)\" != $DEVICE ] ; then\n\t\trm
      #       $OSD_BLOCK_PATH\n\tfi\n\n\t# ceph-volume raw mode only supports bluestore
      #       so we don't need to pass a store flag\n\tceph-volume raw activate --device
      #       \"$DEVICE\" --no-systemd --no-tmpfs\nfi\n"
      #     env:
      #     - name: CEPH_VOLUME_DEBUG
      #       value: "1"
      #     - name: CEPH_VOLUME_SKIP_RESTORECON
      #       value: "1"
      #     - name: DM_DISABLE_UDEV
      #       value: "1"
      #     - name: ROOK_CEPH_MON_HOST
      #       valueFrom:
      #         secretKeyRef:
      #           key: mon_host
      #           name: rook-ceph-config
      #     - name: CEPH_ARGS
      #       value: -m $(ROOK_CEPH_MON_HOST)
      #     - name: ROOK_BLOCK_PATH
      #       value: /dev/sdb
      #     - name: ROOK_METADATA_DEVICE
      #     - name: ROOK_WAL_DEVICE
      #     - name: ROOK_OSD_ID
      #       value: "0"
      #     envFrom:
      #     - configMapRef:
      #         name: rook-ceph-osd-env-override
      #         optional: true
      #     image: quay.io/ceph/ceph:v18.2.1
      #     imagePullPolicy: IfNotPresent
      #     name: activate
      #     resources:
      #       limits:
      #         memory: 16Gi
      #       requests:
      #         cpu: "1"
      #         memory: 16Gi
      #     securityContext:
      #       privileged: true
      #       runAsUser: 0
      #     terminationMessagePath: /dev/termination-log
      #     terminationMessagePolicy: File
      #     volumeMounts:
      #     - mountPath: /var/lib/ceph/osd/ceph-0
      #       name: activate-osd
      #     - mountPath: /dev
      #       name: devices
      #     - mountPath: /etc/temp-ceph
      #       name: rook-config-override
      #       readOnly: true
      #     - mountPath: /etc/ceph/admin-keyring-store/
      #       name: rook-ceph-admin-keyring
      #       readOnly: true
      volumes:
        - name: ceph-admin-secret
          secret:
            secretName: rook-ceph-mon
            optional: false
            items:
              - key: ceph-secret
                path: secret.keyring
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
              - key: data
                path: mon-endpoints
        - hostPath:
          path: /dev
          type: ""
          name: devices
        - hostPath:
            path: /var/lib/rook/rook-ceph/cd940091-c635-449f-92d4-d017f5f8175d_32ca9167-1d8d-4611-b862-4c5df148e60c
            type: DirectoryOrCreate
          name: activate-osd
        - name: ceph-config
          emptyDir: {}
        - name: rook-config-override
          projected:
            defaultMode: 420
            sources:
            - configMap:
                items:
                - key: config
                  mode: 292
                  path: ceph.conf
                name: rook-config-override
        - name: rook-ceph-admin-keyring
          secret:
            defaultMode: 420
            secretName: rook-ceph-admin-keyring
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5