apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres
  namespace: mattermost
type: kubernetes.io/opaque
stringData:
  DB_CONNECTION_CHECK_URL: "postgres://###ZARF_VAR_MATTERMOST_DB_USERNAME###:###ZARF_VAR_MATTERMOST_DB_PASSWORD###@###ZARF_VAR_MATTERMOST_DB_EXTERNAL_NAME###:5432/###ZARF_VAR_MATTERMOST_DB_NAME###?connect_timeout=10&sslmode=disable"
  DB_CONNECTION_STRING: "postgres://###ZARF_VAR_MATTERMOST_DB_USERNAME###:###ZARF_VAR_MATTERMOST_DB_PASSWORD###@###ZARF_VAR_MATTERMOST_DB_EXTERNAL_NAME###:5432/###ZARF_VAR_MATTERMOST_DB_NAME###?connect_timeout=10&sslmode=disable"
