options:
  log_level: info
shared:
  DOMAIN: mtsi-dev.bigbang.dev
variables:
  init:
    # TODO - remove this if/when functionality is restored upstream
    REGISTRY_HPA_ENABLE: false
  metallb:
    IP_ADDRESS_POOL: "10.0.120.50-10.0.120.59"
  core:
    ADMIN_TLS_CERT: replace-me-cert
    ADMIN_TLS_KEY: replace-me-key
    TENANT_TLS_CERT: replace-me-cert
    TENANT_TLS_KEY: replace-me-key
  keycloak-database-manifests:
    KEYCLOAK_DB_EXTERNAL_NAME: "keycloak-pg.mtsi-dev.bigbang.dev"
  uds-idam:
    KEYCLOAK_DB_USERNAME: "postgres"
    KEYCLOAK_DB_PASSWORD: "replace-me-db-passwords"
    KEYCLOAK_DB_NAME: "keycloakdb"
    KEYCLOAK_DB_ENDPOINT: "keycloak-postgres.keycloak.svc.cluster.local"
    KEYCLOAK_VALUES: "our-keycloak-values.yaml"
  gitlab-database-secret:
    GITLAB_DB_PASSWORD: "replace-me-db-passwords"
  gitlab-object-store:
    ENDPOINT: "http://swf.objects.mtsi.bigbang.dev"
    ACCESS_KEY: "replace-me-object-store-access-key"
    SECRET_KEY: "replace-me-object-store-secret-key"
  gitlab:
    GITLAB_DB_NAME: "gitlabdb"
    GITLAB_DB_USERNAME: "postgres"
    GITLAB_DB_ENDPOINT: "gitlab-pg.mtsi-dev.bigbang.dev"
    GITLAB_PAGES_ENABLED: "true"
    GITLAB_SIGNUP_ENABLED: "false"
    GITLAB_BACKUP_SCHEDULE: "0 3 * * *"
    GITLAB_BACKUP_EXTRA_ARGS: "--skip artifiacts,registry"
    BUCKET_SUFFIX: "-dev"
    GITLAB_REDIS_ENDPOINT: "redis-master.dev-redis.svc.cluster.local"
  sonarqube-database-secret:
    SONARQUBE_DB_PASSWORD: "replace-me-db-passwords"
  sonarqube:
    SONARQUBE_IDAM_REALM_URL: "https://keycloak.mtsi-dev.bigbang.dev/auth/realms/baby-yoda"
    # db config
    SONARQUBE_DB_NAME: "sonarqubedb"
    SONARQUBE_DB_USERNAME: "postgres"
    SONARQUBE_DB_ENDPOINT: "sonarqube-pg.mtsi-dev.bigbang.dev"
  jira-database-secret:
    JIRA_DB_PASSWORD: "replace-me-db-passwords"
  jira:
    JIRA_DB_NAME: "jiradb"
    JIRA_DB_USERNAME: "postgres"
    JIRA_LOCAL_HOME_ENABLED: "true"
    JIRA_LOCAL_HOME_SIZE: "128Gi"
    JIRA_RWO_STORAGE_CLASS: "ceph-block"
    JIRA_DB_ENDPOINT: "jira-pg.mtsi-dev.bigbang.dev"
  confluence-database-secret:
    CONFLUENCE_DB_PASSWORD: "replace-me-db-passwords"
  confluence:
    CONFLUENCE_DB_NAME: "confluencedb"
    CONFLUENCE_DB_USERNAME: "postgres"
    CONFLUENCE_LOCAL_HOME_ENABLED: "true"
    CONFLUENCE_LOCAL_HOME_SIZE: "128Gi"
    CONFLUENCE_RWO_STORAGE_CLASS: "ceph-block"
    CONFLUENCE_DB_ENDPOINT: "confluence-pg.mtsi-dev.bigbang.dev"
  mattermost:
    ACCESS_KEY: "replace-me-object-store-access-key"
    SECRET_KEY: "replace-me-object-store-secret-key"
    DB_PASSWORD: "replace-me-db-passwords"
    DB_USERNAME: "postgres"
    DB_NAME: "mattermostdb"
    DB_ENDPOINT: "mattermost-pg.mtsi-dev.bigbang.dev"
    DB_OPTIONS: "?connect_timeout=10&sslmode=disable"
    OBJECT_STORE_SECURE: "false"
    OBJECT_STORE_ENDPOINT: "swf.objects.mtsi.bigbang.dev"
    OBJECT_STORE_BUCKET: "mattermost-bucket-dev"
  nexus:
    NEXUS_DB_NAME: "nexusdb"
    NEXUS_DB_USERNAME: "postgres"
    NEXUS_DB_ENDPOINT: "nexus-pg.mtsi-dev.bigbang.dev"
    POSTGRES_DB_PASSWORD: "replace-me-db-passwords"
    NEXUS_SSO_ENABLED: "false"
    NEXUS_SSO_IDP_ENTITY_ID: ""
    NEXUS_SSO_IDP_USERNAME_ATTRIBUTE: ""
    NEXUS_SSO_IDP_FIRSTNAME_ATTRIBUTE: ""
    NEXUS_SSO_IDP_LASTNAME_ATTRIBUTE: ""
    NEXUS_SSO_IDP_EMAIL_ATTRIBUTE: ""
    NEXUS_SSO_IDP_GROUPS_ATTRIBUTE: ""
    NEXUS_SSO_IDP_VALIDATE_RESPONSE_SIGNATURE: ""
    NEXUS_SSO_IDP_VALIDATE_ASSERTION_SIGNATURE: ""
    NEXUS_SSO_IDP_METADATA: ''
    NEXUS_SSO_REALM: "[]"
    NEXUS_SSO_ROLE: "[]"
