options:
  log_level: info
shared:
  DOMAIN: mtsi.bigbang.dev
variables:
  init:
    # TODO - remove this if/when functionality is restored upstream
    REGISTRY_HPA_ENABLE: false
    CEPH_OSD_MEM_REQUESTS: "4Gi"
    CEPH_OSD_MEM_LIMITS: "4Gi"
    ENABLE_CEPH_TOOLBOX: "true"
  metallb:
    # Replace with a valid IP address range
    IP_ADDRESS_POOL: "10.0.120.70-10.0.120.79"
  keycloak-configuration:
    CONFIG_PKG_FULLPATH: "zarf-package-keycloak-identity-config-amd64-0.0.1.tar.zst"
  core:
    # CERT values must be base64 encoded
    ADMIN_TLS_CERT: replace-me-cert
    ADMIN_TLS_KEY: replace-me-key
    TENANT_TLS_CERT: replace-me-cert
    TENANT_TLS_KEY: replace-me-key
    KEYCLOAK_DB_USERNAME: "postgres"
    KEYCLOAK_DB_PASSWORD: "replace-me-db-passwords"
    KEYCLOAK_DB_NAME: "keycloakdb"
    KEYCLOAK_DB_ENDPOINT: "keycloak-pg.mtsi.bigbang.dev"
    VELERO_BUCKET_PROVIDER_URL: "http://swf.objects.mtsi.bigbang.dev"
    VELERO_BUCKET: "velero-bucket-test"
    VELERO_BUCKET_REGION: "us-east-1"
    VELERO_BUCKET_KEY: "replace-me-object-store-access-key"
    VELERO_BUCKET_KEY_SECRET: "replace-me-object-store-secret-key"
  gitlab-database-secret:
    GITLAB_DB_PASSWORD: "replace-me-db-passwords"
  gitlab-object-store:
    ENDPOINT: "http://swf.objects.mtsi.bigbang.dev"
    ACCESS_KEY: "replace-me-object-store-access-key"
    SECRET_KEY: "replace-me-object-store-secret-key"
  gitlab:
    GITLAB_DB_NAME: "gitlabdb"
    GITLAB_DB_USERNAME: "postgres"
    GITLAB_DB_ENDPOINT: "gitlab-pg.mtsi.bigbang.dev"
    GITLAB_PAGES_ENABLED: "true"
    GITLAB_SIGNUP_ENABLED: "false"
    GITLAB_BACKUP_SCHEDULE: "0 3 * * *"
    GITLAB_BACKUP_EXTRA_ARGS: "--skip artifiacts,registry"
    BUCKET_SUFFIX: "-test"
    GITLAB_REDIS_ENDPOINT: "redis-master.dev-redis.svc.cluster.local"
    WEBSERVICE_REPLICAS: 3
    WEBSERVICE_WORKERS: 4
    WEBSERVICE_HPA:
      cpu:
        targetAverageValue: 1600m
    WEBSERVICE_RESOURCES:
      limits:
        cpu: 8000m
        memory: 8G
      requests:
        cpu: 4000m
        memory: 5G
    MIGRATIONS_RESOURCES:
      limits:
        cpu: 500m
        memory: 4G
    WORKHORSE_RESOURCES:
      limits:
        memory: 100M
      requests:
        cpu: 10m
        memory: 10M
    SIDEKIQ_REPLICAS: 3
    SIDEKIQ_HPA:
      cpu:
        targetAverageValue: 700m
    SIDEKIQ_RESOURCES:
      limits:
        cpu: 2000m
        memory: 4G
      requests:
        cpu: 1000m
        memory: 2G
    GITALY_RESOURCES:
      limits:
        cpu: 4000m
        memory: 15G
      requests:
        cpu: 4000m
        memory: 15G
    REGISTRY_REPLICAS: 2
    SHELL_REPLICAS: 2
  sonarqube-database-secret:
    SONARQUBE_DB_PASSWORD: "replace-me-db-passwords"
  sonarqube:
    # db config
    SONARQUBE_DB_NAME: "sonarqubedb"
    SONARQUBE_DB_USERNAME: "postgres"
    SONARQUBE_DB_ENDPOINT: "sonarqube-pg.mtsi.bigbang.dev"
  jira-database-secret:
    JIRA_DB_PASSWORD: "replace-me-db-passwords"
  jira:
    JIRA_DB_NAME: "jiradb"
    JIRA_DB_USERNAME: "postgres"
    JIRA_LOCAL_HOME_ENABLED: "true"
    JIRA_LOCAL_HOME_SIZE: "128Gi"
    JIRA_RWO_STORAGE_CLASS: "ceph-block"
    JIRA_DB_ENDPOINT: "jira-pg.mtsi.bigbang.dev"
  confluence-database-secret:
    CONFLUENCE_DB_PASSWORD: "replace-me-db-passwords"
  confluence:
    CONFLUENCE_DB_NAME: "confluencedb"
    CONFLUENCE_DB_USERNAME: "postgres"
    CONFLUENCE_LOCAL_HOME_ENABLED: "true"
    CONFLUENCE_LOCAL_HOME_SIZE: "128Gi"
    CONFLUENCE_RWO_STORAGE_CLASS: "ceph-block"
    CONFLUENCE_DB_ENDPOINT: "confluence-pg.mtsi.bigbang.dev"
  mattermost:
    ACCESS_KEY: "replace-me-object-store-access-key"
    SECRET_KEY: "replace-me-object-store-secret-key"
    DB_PASSWORD: "replace-me-db-passwords"
    DB_USERNAME: "postgres"
    DB_NAME: "mattermostdb"
    DB_ENDPOINT: "mattermost-pg.mtsi.bigbang.dev"
    DB_OPTIONS: "?connect_timeout=10&sslmode=disable"
    OBJECT_STORE_SECURE: "false"
    OBJECT_STORE_ENDPOINT: "swf.objects.mtsi.bigbang.dev"
    OBJECT_STORE_BUCKET: "mattermost-bucket-test"
  nexus:
    NEXUS_DB_NAME: "nexusdb"
    NEXUS_DB_USERNAME: "postgres"
    NEXUS_DB_ENDPOINT: "nexus-pg.mtsi.bigbang.dev"
    POSTGRES_DB_PASSWORD: "replace-me-db-passwords"
    NEXUS_SSO_ENABLED: "false"
    NEXUS_SSO_IDP_ENTITY_ID: ""
    NEXUS_SSO_IDP_USERNAME_ATTRIBUTE: ""
    NEXUS_SSO_IDP_FIRSTNAME_ATTRIBUTE: ""
    NEXUS_SSO_IDP_LASTNAME_ATTRIBUTE: ""
    NEXUS_SSO_IDP_EMAIL_ATTRIBUTE: ""
    NEXUS_SSO_IDP_GROUPS_ATTRIBUTE: ""
    NEXUS_SSO_IDP_VALIDATE_RESPONSE_SIGNATURE: ""
    NEXUS_SSO_IDP_VALIDATE_ASSERTION_SIGNATURE: ""
    NEXUS_SSO_IDP_METADATA: ''
    NEXUS_SSO_REALM: "[]"
    NEXUS_SSO_ROLE: "[]"
