apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: gitlab-certificates
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - policies:
        - DisallowPrivileged
        - RequireNonRootUser
      matcher:
        namespace: gitlab
        name: ".*"
      title: "gitlab exemptions"
      description: "Gitlab's certificates container needs write access to the following paths in order to load custom CA certificates:
        - `/usr/share/pki/ca-trust-source/anchors/`
        - `/etc/pki/ca-trust/extracted/openssl/`
        - `/etc/pki/ca-trust/extracted/java/`
        - `/etc/pki/ca-trust/extracted/edk2/`"

---
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: gitaly-cgroups
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - policies:
        - RestrictHostPathWrite
        - RestrictVolumeTypes
        - RequireNonRootUser
        - DropAllCapabilities
      matcher:
        namespace: gitlab
        name: "gitlab-gitaly.*"
      title: "gitlab gitaly exemptions"
      description: "Gitaly is setting cgroup resource limitations to reduce the risk of a single large git call producing an OOM pod termination."
