apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: rook-ceph
  namespace: uds-policy-exemptions
spec:
  exemptions:
    - policies:
        - DisallowHostNamespaces
        - DisallowPrivileged
        - DisallowSELinuxOptions
        - DropAllCapabilities
        - RequireNonRootUser
        - RestrictCapabilities
        - RestrictHostPathWrite
        - RestrictHostPorts
        - RestrictProcMount
        - RestrictSeccomp
        - RestrictSELinuxType
        - RestrictVolumeTypes
      matcher:
        namespace: rook-ceph
        name: "^rook-*"
        kind: pod
      title: "rook-ceph exemptions"
      description: "Rook ceph needs exemptions"
    - policies:
        - DisallowHostNamespaces
        - DisallowPrivileged
        - DisallowSELinuxOptions
        - DropAllCapabilities
        - RequireNonRootUser
        - RestrictCapabilities
        - RestrictHostPathWrite
        - RestrictHostPorts
        - RestrictProcMount
        - RestrictSeccomp
        - RestrictSELinuxType
        - RestrictVolumeTypes
      matcher:
        namespace: rook-ceph
        name: "^csi-*"
        kind: pod
      title: "rook-ceph csi exemptions"
      description: "Rook ceph needs exemptions"
