apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: keycloak-non-root-group-exception
  namespace: keycloak
spec:
  exceptions:
  - policyName: require-non-root-group
    ruleNames:
    - run-as-group
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - keycloak
        names:
        - keycloak-0
