apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: mattermost-postgres-external-names-exception
  namespace: mattermost
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - mattermost
        names:
        - mattermost-postgres
