name: Tag, Release and Publish UDS Bundle

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  tag-new-version:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4.1.3
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> $GITHUB_OUTPUT

  # Publish the uds bundle
  publish-uds-bundle-eksd:
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    uses: ./.github/workflows/publish-bundle-eksd.yaml
    secrets: inherit

  # Publish the uds bundle
  publish-uds-bundle-rke2:
    needs: tag-new-version
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    uses: ./.github/workflows/publish-bundle-rke2.yaml
    secrets: inherit
