name: Tag, Release and Publish UDS Bundle

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  tag-new-version:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-flag.outputs.release_created }}
      release_tag: ${{ steps.release-tag.outputs.release_tag }}
    steps:
      - name: Create Release Tag
        id: tag
        uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4
        with:
          command: manifest  # use configs in release-please-config.json
      - id: release-flag
        run: echo "release_created=${{ steps.tag.outputs.release_created || false }}" >> "$GITHUB_OUTPUT"
      - id: release-tag
        run: echo "release_tag=${{ steps.tag.outputs.version || false }}" >> "$GITHUB_OUTPUT"

  # Publish the uds bundle
  publish-uds-bundle-rke2:
    needs: tag-new-version
    permissions: write-all
    if: ${{ needs.tag-new-version.outputs.release_created == 'true'}}
    uses: ./.github/workflows/publish-bundle-rke2.yaml
    with:
      tag-name: ${{ needs.tag-new-version.outputs.release_tag }}
    secrets: inherit
